default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  port: <%= ENV.fetch("DATABASE_PORT", "5432") %>
  pool: <%= ENV.fetch("DATABASE_POOL", "5") %>

development:
  <<: *default
  database: doorprize_app_development

test:
  <<: *default
  database: doorprize_app_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "doorprize_app_production") %>
  # Production-specific optimizations
  pool: <%= ENV.fetch("DATABASE_POOL", "10") %>
  timeout: <%= ENV.fetch("DATABASE_TIMEOUT", "5000") %>
  
  # SSL configuration for production databases
  sslmode: <%= ENV.fetch("DATABASE_SSLMODE", "prefer") %>
  
  # Connection URL support (for services like Heroku, Railway, etc.)
  url: <%= ENV["DATABASE_URL"] if ENV["DATABASE_URL"].present? %>
